version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: copy-webpack-plugin
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: postcss-loader
    versions:
    - 5.0.0
    - 5.1.0
  - dependency-name: zrender
    versions:
    - 5.0.3
    - 5.0.4
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
